### ISSUE TITLE
Using Win-1251

### ISSUE THREAD

**Issue by Rassska** [Quied/List-Employees#1]
Avoid using win-1251 when you write a code. 
If you encode your `Source.cpp` into the UTF-8 it looks like that:
![Screenshot from 2021-11-17 02-44-02](https://user-images.githubusercontent.com/73281386/142083906-f19d984c-9ec8-4e31-91be-58ae5688baff.png)

**Comment by Quied** [comment]
Oh, ok, i thought this mistake with Github encode
